/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automationRegistrarSol from "./AutomationRegistrar.sol";
export type { automationRegistrarSol };
export type { AggregatorV3Interface } from "./AggregatorV3Interface";
export type { AutomationCompatibleInterface } from "./AutomationCompatibleInterface";
export type { LinkTokenInterface } from "./LinkTokenInterface";
